---

- name: install website service
  become: True
  hosts: homecloud
  tags:
    - service
    - service_web
  roles:
    - service_template_stateless
  vars:
    homecloud_fqdn: homecloud.test
    app_name: webtest
    deployment_container_image: paulbouwer/hello-kubernetes:1.5