---

- name: install example service
  become: True
  hosts: homecloud
  tags:
    - service
    - service_web
  roles:
    - service_template
  vars_files:
    - 'settings_{{ env }}.yml'
  vars:
    app_name: webtest
    app_state: present
    app_port: 8080
    host_port: 80
    container_image: paulbouwer/hello-kubernetes:1.5