---
kernel_modules: ['overlay', 'br_netfilter']
kernel_parameters: {
  net.bridge.bridge-nf-call-iptables: 1,
  net.bridge.bridge-nf-call-ip6tables: 1,
  net.ipv4.ip_forward: 1,
}
cgroup_driver: systemd

cert_manager_version: 'v1.2.0'
cert_manager_url: 'https://github.com/jetstack/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.yaml'
cert_manager_namespace: cert-manager

ingress_nginx_version: 'v1.0.4'
# 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-{{ ingress_nginx_version }}/deploy/static/provider/cloud/deploy.yaml'
ingress_nginx_url: 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-{{ ingress_nginx_version }}/deploy/static/provider/baremetal/deploy.yaml'
ingress_nginx_namespace: ingress-nginx

service_volume_name: '{{ homecloud_service_volume_name }}'
service_volume_path: '{{ homecloud_service_volume_dir }}'
service_volume_claim_name: '{{ homecloud_service_volume_claim_name }}'
service_volume_claim_namespace: '{{ homecloud_service_namespace }}'
service_volume_claim_size: 5Gi