---
app_fqdn: '{{ app_name }}.{{ homecloud_fqdn }}'
deployment_file: '{{ persistence_enabled | ternary("deployment_stateful", "deployment")}}'


_pod_sec_ctx:
  securityContext:
    runAsUser: 10000
    runAsGroup: 10000
    privileged: false
    runAsNonRoot: true
    allowPrivilegeEscalation: false

# same as in PodSpec, but overwrites def at Pod level
_container_sec_ctx: '{{ _pod_sec_ctx }}'

pod_sec_ctx: '{{ _pod_sec_ctx.securityContext | from_yaml }}'
container_sec_ctx: '{{ _container_sec_ctx.securityContext | from_yaml }}'