---
# tasks file for service_web

- name: Ensure k8s module dependencies are installed.
  pip:
    name: openshift
    state: present

- name: Create {{ app_name }} and wait until it is ready.
  community.kubernetes.k8s:
    state: '{{ app_state }}'
    wait: true
    template: '{{ item }}.yml.j2'
  with_items:
    - service
    - deployment