---
# tasks file for service_web

- name: Ensure k8s module dependencies are installed.
  pip:
    name: openshift
    state: present

- name: Ensure {{ app_name }} is {{ app_state }}
  community.kubernetes.k8s:
    state: '{{ app_state }}'
    wait: true
    template: '{{ item }}.yml.j2'
  with_items:
    - service
    - '{{ deployment_file }}'
    - ingress