---
# tasks file for homecloud_host_setup

- name: base packages
  apt: 
    name: '{{ item }}' 
    state: present
  with_items:
    - gpg
    - python3
    - python3-pip

- name: set timezone
  import_tasks: time.yml
  tags: time

- name: basic security configuration
  import_role:
    name: homecloud_host_security
  tags:
    - security