---
# tasks file for homecloud_host_setup

- name: base packages
  apt: name=gpg state=present

- name: set timezone
  import_tasks: time.yml
  tags: time

- name: basic security configuration
  import_role:
    name: homecloud_host_security
  tags:
    - security