---
# defaults file for service_web

app_state: present
app_fqdn: '{{ app_name }}.{{ homecloud_fqdn }}'
service_namespace: '{{ homecloud_service_namespace }}'
deployment_replicas: 1
persistence_enabled: False
service_pv_name: '{{ homecloud_service_volume_name }}'
service_pvc_name: '{{ homecloud_service_volume_claim_name }}'