---

- name: ensure cert-manager namespace exists
  community.kubernetes.k8s:
    name: '{{ item  }}'
    api_version: v1
    kind: Namespace
    state: present
  with_items:
    - '{{ cert_manager_namespace }}'

- name: ensure jetstack helm repo is added
  community.kubernetes.helm_repository:
    state: present
    name: jetstack
    repo_url: 'https://charts.jetstack.io'

- name: ensure cert-manager helm chart is installed
  community.kubernetes.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: '{{ cert_manager_version }}'
    release_namespace: '{{ cert_manager_namespace }}'
    create_namespace: true
    atomic: yes
    update_repo_cache: yes
    wait: true
    values:
      installCrds: true

