---
# tasks file for homecloud_kubernetes

- name: ensure container engine is installed
  import_role:
    name: geerlingguy.docker
  tags:
    - container_engine
    - docker

- name: ensure kubernetes is running
  import_role:
    name: geerlingguy.kubernetes
  tags:
    - kubernetes

- name: ensure dependencies for community.kubernetes.k8s exist
  pip:
    name: openshift
    state: present

- name: ensure namespace for services exists
  community.kubernetes.k8s:
    name: '{{ kubernetes_service_namespace }}'
    api_version: v1
    kind: Namespace
    state: present

- name: ensure helm is installed
  import_role: 
    name: geerlingguy.helm
  tags:
    - helm

- name: ensure storage is prepared
  import_tasks: storage.yml
  tags:
    - storage