---
# tasks file for homecloud_kubernetes

- name: ensure kernel is set up correctly
  import_tasks: kernel.yml
  tags:
    - kernel

# vars required for docker: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker
- name: ensure container engine is installed
  import_role:
    name: geerlingguy.docker
  vars:
    docker_daemon_options:
      exec-opts: ['native.cgroupdriver={{ cgroup_driver }}']
      storage-driver: 'overlay2'
  tags:
    - container_engine
    - docker

- name: ensure kubernetes is running
  import_role:
    name: geerlingguy.kubernetes
  vars:
    kubernetes_role: master
    kubernetes_allow_pods_on_master: true
    kubernetes_config_kubelet_configuration:
      cgroupDriver: '{{ cgroup_driver }}'
    #kubernetes_apiserver_advertise_address: '192.168.60.2'
  tags:
    - kubernetes

# i.e. used for webhooks 
- name: ensure master-local pods can communicate with api-server
  community.general.ufw:
    # == "ufw allow in on cni0" 
    rule: allow
    interface_in: cni0

- name: ensure dependencies for community.kubernetes.k8s exist
  pip:
    name: openshift
    state: present

- name: ensure namespace for services exists
  community.kubernetes.k8s:
    name: '{{ homecloud_service_namespace }}'
    api_version: v1
    kind: Namespace
    state: present

- name: ensure helm is installed
  import_role: 
    name: geerlingguy.helm
  tags:
    - helm

- name: ensure storage is prepared
  import_tasks: storage.yml
  tags:
    - storage

- name: ensure cert-manager is installed
  import_tasks: cert_manager.yml
  tags:
    - cert_manager
  when: platform_env == 'prod'

- name: ensure ingress is installed
  import_tasks: ingress.yml
  tags:
    - ingress
