---
# tasks file for homecloud_kubernetes

- name: ensure container engine is installed
  import_role:
    name: geerlingguy.docker

- name: ensure kubernetes is running
  import_role:
    name: geerlingguy.kubernetes